#6000是eureka 6001是config 6003是feigh 6004是ribbon 6005是zull 61xx是服务
server:
  port: 6001
spring:
  application:
    name: springbootConfig
  profiles:
    active: subversion
  cloud:
    config:
      server:
        svn:
          uri: https://47.93.41.224:4433/svn/Runnor.CyjTest/SpringCloud/Config
          #username: *****
          #password: *****
          default-label:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6000/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
