#6000是eureka 6001是config 6003是feigh 6004是ribbon 6005是zull 61xx是服务
spring:
  application:
    name : springbootZuul

server:
  port : 6005

eureka:
  client:
    service-url:
      defaultZone : http://localhost:6000/eureka/

zuul:
  routes:
    sbService :
      path : /sbService/**
      serviceId : springbootService
